version: '3.5'

services:
    postgres:
        image: postgres:14
        container_name: postgres-chatty-app
        networks:
            - chatty-app
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
    server:
        container_name: chatty-app-server
        image: chatty-app-server
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev
        depends_on:
            - postgres
        networks:
            - chatty-app
    adminer:
        image: adminer
        container_name: chatty-app-adminer
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        networks:
            - chatty-app

networks:
    chatty-app:
        external:
            name: chatty-app

volumes:
    postgres:
